apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-ssl-config
  namespace: linux-monitoring
data:
  ssl.conf: |
    <VirtualHost *:443>
        ServerName kubearena.pratikrastogi.co.in
        DocumentRoot /var/www/html

        SSLEngine on
        SSLCertificateFile /etc/ssl/kube/tls.crt
        SSLCertificateKeyFile /etc/ssl/kube/tls.key

        <Directory /var/www/html>
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog /proc/self/fd/2
        CustomLog /proc/self/fd/1 combined
    </VirtualHost>

