apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanup-worker
  namespace: linux-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleanup-worker
  template:
    metadata:
      labels:
        app: cleanup-worker
    spec:
      containers:
      - name: worker
        image: docker.io/pratikrastogi/provision_worker
        command: ["python","/opt/lab/cleanup_worker.py"]

