apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labs-rwx
  namespace: linux-monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs-rwx
  resources:
    requests:
      storage: 20Gi

