apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-ui
  namespace: linux-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-ui
  template:
    metadata:
      labels:
        app: php-ui
    spec:
      containers:
      - name: php-ui
        image: pratikrastogi/linux-monitoring:2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-ui
  namespace: linux-monitoring
spec:
  type: NodePort
  selector:
    app: php-ui
  ports:
  - port: 80
    nodePort: 30080

