apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-ui-ingress
  namespace: linux-monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - kubearena.pratikrastogi.co.in
    secretName: kubearena-tls
  rules:
  - host: kubearena.pratikrastogi.co.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: php-ui
            port:
              number: 80

