apiVersion: apps/v1
kind: Deployment
metadata:
  name: provision-worker
  namespace: linux-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provision-worker
  template:
    metadata:
      labels:
        app: provision-worker
    spec:
      containers:
      - name: provision-worker
        image: docker.io/pratikrastogi/provision_worker:1.0
        command: ["python","provision_worker.py"]
