apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal-gateway
  namespace: linux-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminal-gateway
  template:
    metadata:
      labels:
        app: terminal-gateway
    spec:
      containers:
      - name: gateway
        image: pratikrastogi/terminal-gateway
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: terminal-gateway
  namespace: linux-monitoring
spec:
  selector:
    app: terminal-gateway
  ports:
  - port: 3000
    targetPort: 3000

