apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
  namespace: linux-monitoring
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "49251245482-6bee9qthlqrgj3qq11jao3ncui4ep0n3.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: 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
  GOOGLE_REDIRECT_URI: "http://monitor.pratikrastogi.co.in/oauth/google_callback.php"
